import { handleackMS, handleARUP, handleaskchaa, handleASS, handleAUTH, handleBB, handleBD, handleBN, handleCC, handleCharsCheck, handleCI, handleCT, handleDONE, handleEI, handleEM, handleFA, handleFL, handleFM, handleHI, handleHP, handleID, handleJD, handleKB, handleKK, handleLE, handleMC, handleMM, handleMS, handlePN, handlePR, handlePU, handlePV, handleRC, handleRD, handleRM, handleRMC, handleRT, handleSC, handleSI, handleSM, handleSP, handleTI, handleZZ } from './handlers/Handler'


export const packets = {
  MS: handleMS,
  CT: handleCT,
  MC: handleMC,
  RMC: handleRMC,
  CI: handleCI,
  SC: handleSC,
  EI: handleEI,
  FL: handleFL,
  LE: handleLE,
  EM: handleEM,
  FM: handleFM,
  FA: handleFA,
  SM: handleSM,
  MM: handleMM,
  BD: handleBD,
  BB: handleBB,
  KB: handleKB,
  KK: handleKK,
  DONE: handleDONE,
  BN: handleBN,
  HP: handleHP,
  RT: handleRT,
  TI: handleTI,
  ZZ: handleZZ,
  HI: handleHI,
  ID: handleID,
  PN: handlePN,
  SI: handleSI,
  ARUP: handleARUP,
  AUTH: handleAUTH,
  askchaa: handleaskchaa,
  CC: handleCC,
  RC: handleRC,
  RM: handleRM,
  RD: handleRD,
  CharsCheck: handleCharsCheck,
  PV: handlePV,
  ASS: handleASS,
  ackMS: handleackMS,
  SP: handleSP,
  JD: handleJD,
  PU: handlePU,
  PR: handlePR,
  decryptor: () => {},
  CHECK: () => {},
  CH: () => {},
};
